### ISSUE TITLE
Endpoint depreciated 

### ISSUE THREAD

**Issue by mrNERDbanger** [jordanmerrick/scriptable#2]
Keep getting this error when trying to run this:

{"error":"Endpoint deprecated: Please update your App.","response":null,"error_description":""}

**Comment by jordanmerrick** [comment]
What specifically are you running?

**Comment by mrNERDbanger** [comment]
The scriptable widgets for Tesla. I know all the other shortcuts now use the Auth app but when I click that one it asks for email and password and then says that error in the log.

**Comment by jordanmerrick** [comment]
Ah I see. I've recently updated the shortcuts so they can work with Tesla's new authentication process. I've updated the README with the details. Download the required iOS app, install the new shortcut, and you should be able to get your access token and set up the scripts.
